import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const manifest = JSON.parse(fs.readFileSync(path.join(root, "module.json"), "utf8"));
const packageJson = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));

assert.equal(manifest.id, path.basename(root));
assert.equal(manifest.compatibility.minimum, "13");
assert.equal(manifest.compatibility.maximum, "13");
assert.equal(manifest.url, "https://github.com/Kciquehn/symbaroum-hud");
assert.equal(manifest.manifest, "https://github.com/Kciquehn/symbaroum-hud/releases/latest/download/module.json");
assert.equal(manifest.download, "https://github.com/Kciquehn/symbaroum-hud/releases/latest/download/symbaroum-hud.zip");
assert.equal(manifest.readme, "https://github.com/Kciquehn/symbaroum-hud/blob/main/README.md");
assert.equal(manifest.changelog, "https://github.com/Kciquehn/symbaroum-hud/blob/main/CHANGELOG.md");
assert.equal(manifest.license, "https://github.com/Kciquehn/symbaroum-hud/blob/main/LICENSE");
assert.equal(manifest.bugs, "https://github.com/Kciquehn/symbaroum-hud/issues");
assert.ok(manifest.esmodules.includes("scripts/main.mjs"));
assert.ok(fs.existsSync(path.join(root, "scripts", "services", "character-creator-service.mjs")), "Missing character creator service");
assert.ok(fs.existsSync(path.join(root, "scripts", "data", "core-occupations.mjs")), "Missing core occupations data");
assert.ok(fs.existsSync(path.join(root, "scripts", "data", "core-attributes.mjs")), "Missing core attributes data");
assert.ok(fs.existsSync(path.join(root, "scripts", "data", "character-creation-abilities.mjs")), "Missing character creation Abilities data");
assert.ok(fs.existsSync(path.join(root, "LICENSE")), "Missing LICENSE file");
assert.ok(fs.existsSync(path.join(root, "CHANGELOG.md")), "Missing CHANGELOG.md file");
assert.ok(fs.existsSync(path.join(root, "styles", "character-creator-theme.css")), "Missing Character Creator theme");
assert.ok(fs.existsSync(path.join(root, "FOUNDRY-PACKAGE-DESCRIPTION.html")), "Missing Foundry package description HTML");
assert.ok(fs.existsSync(path.join(root, "assets", "overlays", "low-health-blood.png")), "Missing low-health blood overlay");
assert.ok(fs.existsSync(path.join(root, "assets", "overlays", "button-cracks.png")), "Missing per-button cracks overlay");
for (const raceArt of ["ambrian.webp", "barbarian.webp", "changeling.webp", "goblin.webp", "goblin-ogre.webp"]) {
  assert.ok(fs.existsSync(path.join(root, "assets", "races", raceArt)), `Missing race artwork: ${raceArt}`);
}
assert.ok(fs.existsSync(path.join(root, ".github", "workflows", "release.yml")), "Missing GitHub release workflow");
assert.ok(fs.existsSync(path.join(root, ".github", "workflows", "check.yml")), "Missing GitHub check workflow");
assert.equal(packageJson.version, manifest.version, "package.json and module.json versions must match");
assert.equal(packageJson.engines.node, ">=20");

const checkWorkflow = fs.readFileSync(
  path.join(root, ".github", "workflows", "check.yml"),
  "utf8"
);
const releaseWorkflow = fs.readFileSync(
  path.join(root, ".github", "workflows", "release.yml"),
  "utf8"
);
assert.match(checkWorkflow, /run: npm test/);
assert.match(releaseWorkflow, /run: npm test/);
assert.match(checkWorkflow, /actions\/checkout@v6/);
assert.match(checkWorkflow, /actions\/setup-node@v6/);
assert.match(checkWorkflow, /node-version: 24/);
assert.match(releaseWorkflow, /actions\/checkout@v6/);
assert.match(releaseWorkflow, /actions\/setup-node@v6/);
assert.match(releaseWorkflow, /softprops\/action-gh-release@v3/);
assert.match(releaseWorkflow, /cp module\.json LICENSE dist\/symbaroum-hud\//);
assert.match(releaseWorkflow, /cp -R assets languages scripts styles templates dist\/symbaroum-hud\//);
assert.doesNotMatch(releaseWorkflow, /rsync/);

for (const relativePath of [
  ...manifest.esmodules,
  ...manifest.styles,
  ...manifest.languages.map((language) => language.path),
  "templates/hud.hbs"
]) {
  assert.ok(fs.existsSync(path.join(root, relativePath)), `Missing manifest asset: ${relativePath}`);
}

const languages = new Map();
for (const file of fs.readdirSync(path.join(root, "languages"))) {
  languages.set(
    file,
    JSON.parse(fs.readFileSync(path.join(root, "languages", file), "utf8"))
  );
}
assert.deepEqual(
  translationKeys(languages.get("en.json")),
  translationKeys(languages.get("pt-BR.json")),
  "English and Brazilian Portuguese must expose the same translation keys"
);

const template = fs.readFileSync(path.join(root, "templates", "hud.hbs"), "utf8");
const application = fs.readFileSync(path.join(root, "scripts", "applications", "symbaroum-hud.mjs"), "utf8");
const actorService = fs.readFileSync(path.join(root, "scripts", "services", "actor-service.mjs"), "utf8");
const characterCreatorService = fs.readFileSync(path.join(root, "scripts", "services", "character-creator-service.mjs"), "utf8");
const coreOccupations = fs.readFileSync(path.join(root, "scripts", "data", "core-occupations.mjs"), "utf8");
const coreAttributes = fs.readFileSync(path.join(root, "scripts", "data", "core-attributes.mjs"), "utf8");
const hooks = fs.readFileSync(path.join(root, "scripts", "hooks.mjs"), "utf8");
const main = fs.readFileSync(path.join(root, "scripts", "main.mjs"), "utf8");
const settings = fs.readFileSync(path.join(root, "scripts", "settings.mjs"), "utf8");
const hotbarShortcuts = fs.readFileSync(
  path.join(root, "scripts", "integrations", "hotbar-shortcuts.mjs"),
  "utf8"
);
const hotbarShortcutService = fs.readFileSync(
  path.join(root, "scripts", "services", "hotbar-shortcut-service.mjs"),
  "utf8"
);
const hotbarCompat = fs.readFileSync(
  path.join(root, "scripts", "compat", "hotbar.mjs"),
  "utf8"
);
const stylesheet = fs.readFileSync(path.join(root, "styles", "symbaroum-hud.css"), "utf8");
const characterCreatorTheme = fs.readFileSync(
  path.join(root, "styles", "character-creator-theme.css"),
  "utf8"
);
assert.match(application, /foundry\.applications\.handlebars\.renderTemplate/);
assert.doesNotMatch(application, /return renderTemplate\(/);
assert.doesNotMatch(characterCreatorService, /continue-later|ContinueLater/);
assert.match(stylesheet, /@import url\("\.\/character-creator-theme\.css"\)/);
assert.match(characterCreatorTheme, /green_flower_light\.webp/);
assert.match(characterCreatorTheme, /--color-charBG:\s*var\(--symba-creator-green-light\) repeat/);
assert.match(characterCreatorTheme, /--title-image:\s*var\(--symba-creator-title\)/);
assert.doesNotMatch(characterCreatorTheme, /--(?:color-charBG|title-image):[^;]*\.\.\/asset\//);
assert.match(characterCreatorTheme, /green_flower_dark\.webp/);
assert.match(characterCreatorTheme, /foreground\.webp/);
assert.match(characterCreatorTheme, /title\.webp/);
assert.match(characterCreatorTheme, /font-family: "Primitive"/);
assert.match(characterCreatorTheme, /\.symbaroum-hud-creation-item-preview[\s\S]*?z-index: 1100 !important/);
assert.match(characterCreatorTheme, /\.symbaroum-hud-abilities-book \.symbaroum-hud-ability-page \{[\s\S]*?border: 0;[\s\S]*?background: transparent;/);
assert.match(characterCreatorTheme, /\.symbaroum-hud-equipment-book/);
assert.match(characterCreatorTheme, /\.symbaroum-hud-equipment-summary/);
assert.match(characterCreatorTheme, /\.symbaroum-hud-equipment-official-text/);
assert.match(characterCreatorTheme, /\.symbaroum-hud-equipment-item-link/);
assert.match(stylesheet, /\.symbaroum-hud-native-ability-sheet \.editor-content \{[^}]*font-size: 0\.72rem;[^}]*line-height: 1\.5;/);
assert.match(stylesheet, /\.symbaroum-hud-native-ability-sheet \.editor-content p \{[^}]*border: 0;[^}]*text-decoration: none;/);
assert.match(stylesheet, /\.symbaroum-hud-native-ability-sheet \.editor-content hr \{ display: none; \}/);
assert.match(stylesheet, /\.symbaroum-hud-native-ability-sheet \.ability :is\(\.novice, \.adept, \.master\) > h1 \{ display: none; \}/);
assert.match(stylesheet, /\.symbaroum-hud-mystical-tradition-hero \{/);
assert.match(stylesheet, /\.symbaroum-hud-mystical-tradition-chapter \{/);
assert.match(stylesheet, /\.symbaroum-hud-mystical-tradition-corruption \{/);
for (const file of scriptFiles(path.join(root, "scripts"))) {
  const source = fs.readFileSync(file, "utf8");
  assert.doesNotMatch(source, /\beval\s*\(/, `${file} must not use eval()`);
  assert.doesNotMatch(source, /\bnew Function\s*\(/, `${file} must not create dynamic functions`);
  assert.doesNotMatch(source, /\bonerror\s*=/i, `${file} must not use inline error handlers`);
  assert.doesNotMatch(source, /\bdebugger\b/, `${file} must not contain debugger statements`);
  assert.doesNotMatch(source, /console\.log\s*\(/, `${file} must not log noisy public output`);
}
assert.match(template, /class="symbaroum-hud-character-card"/);
assert.match(template, /data-symba-weapon-drawn/);
assert.match(template, /data-vitality-state="{{vitalityState}}"/);
assert.match(template, /symbaroum-hud-character-name/);
assert.match(template, /data-action="previous-actor"/);
assert.match(template, /data-action="next-actor"/);
assert.match(template, /symbaroum-hud-actor-cycle/);
assert.match(template, /symbaroum-hud-death-failures/);
assert.match(template, /class="symbaroum-hud-effects"/);
assert.match(template, /#each effects/);
assert.match(template, /data-effect-id="{{id}}"/);
assert.match(template, /class="symbaroum-hud-status-summary"/);
assert.match(template, /class="symbaroum-hud-tactics"/);
assert.match(template, /class="symbaroum-hud-tactics-toggle" data-action="toggle-tactics"/);
assert.match(template, /data-tactics-collapsed="{{tactics\.collapsed}}"/);
assert.match(template, /\{\{\{tactics\.html\}\}\}/);
assert.ok(
  template.indexOf('class="symbaroum-hud-effects"')
    < template.indexOf('class="symbaroum-hud-tactics"'),
  "Active effects must appear above the creature tactics panel"
);
assert.match(template, /actor\.deathFailures/);
assert.match(template, /actor\.vitality\.value/);
assert.match(template, /data-action="modify-vitality"/);
assert.match(template, /data-action="modify-corruption"/);
assert.match(template, /actor\.corruption\.temporary/);
assert.match(template, /data-action="open-actor"/);
assert.match(template, /data-symba-hotbar/);
assert.match(template, /data-action="toggle-hud-collapse"/);
assert.match(template, /data-hud-collapsed="{{hudCollapsed}}"/);
assert.match(template, /data-hud-transition="{{hudTransition}}"/);
assert.match(template, /aria-expanded="{{hudExpanded}}"/);
assert.match(template, /class="symbaroum-hud-info-panel"/);
assert.match(template, /class="symbaroum-hud-economy-panel"/);
assert.match(template, /class="symbaroum-hud-economy-entry"/);
assert.match(template, /class="symbaroum-hud-action-area"/);
assert.match(template, /class="symbaroum-hud-experience-panel"/);
assert.match(template, /#if showEconomy/);
assert.match(template, /#if knowledge\.available/);
assert.match(template, /#if knowledge\.showExperience/);
assert.match(template, /data-knowledge-columns="{{knowledge\.columns}}"/);
assert.match(template, /data-has-experience="{{knowledge\.showExperience}}"/);
assert.match(template, /data-has-knowledge="{{knowledge\.available}}"/);
assert.ok(
  template.indexOf('class="symbaroum-hud-experience-panel"')
    < template.indexOf('class="symbaroum-hud-panel-stack"'),
  "The experience bar must appear above the attack and storage buttons"
);
assert.ok(
  template.indexOf('class="symbaroum-hud-experience-panel"')
    < template.indexOf('class="symbaroum-hud-knowledge-stack"'),
  "The experience bar must appear above the knowledge buttons"
);
assert.match(template, /symbaroum-hud-economy-action/);
assert.match(template, /data-action="open-money"/);
assert.match(template, /info\.money\.thaler/);
assert.match(template, /info\.money\.shilling/);
assert.match(template, /info\.money\.orteg/);
assert.match(template, /info\.load\.current/);
assert.match(template, /info\.load\.capacity/);
assert.match(template, /info\.experience\.available/);
assert.match(template, /info\.experience\.total/);
assert.match(template, /symbaroum-hud-storage-toggle/);
assert.match(template, /symbaroum-hud-panel-toggle symbaroum-hud-storage-toggle/);
assert.match(template, /symbaroum-hud-panel-toggle symbaroum-hud-attacks-toggle/);
assert.match(template, /class="symbaroum-hud-panel-stack"/);
assert.match(template, /class="symbaroum-hud-attacks-panel"/);
assert.match(template, /<ul class="symbaroum-hud-attacks-body"/);
assert.match(template, /<li class="symbaroum-hud-attack-slot">[\s\S]*<button type="button" class="symbaroum-hud-attack-entry"/);
assert.match(template, /class="symbaroum-hud-attack-entry"/);
assert.match(template, /class="symbaroum-hud-attack-label"/);
assert.match(template, /fa-dice-d20/);
assert.doesNotMatch(template, /class="symbaroum-hud-attack-entry" role="listitem"/);
assert.match(template, /class="symbaroum-hud-attacks-empty"/);
assert.match(template, /data-action="toggle-attacks"/);
assert.match(template, /data-action="close-attacks"/);
assert.match(template, /data-action="roll-weapon"/);
assert.match(template, /data-weapon-drop="{{attacks\.canUse}}"/);
assert.match(template, /data-weapon-draggable=/);
assert.match(template, /data-readiness-known="{{readinessKnown}}"/);
assert.match(template, /data-drawn="{{drawn}}"/);
assert.match(template, /class="symbaroum-hud-attack-readiness"/);
assert.match(template, /data-action="sheathe-weapon"/);
assert.match(template, /data-panel="attacks"/);
assert.match(template, /class="symbaroum-hud-knowledge-stack"/);
assert.match(template, /#if actions\.maneuvers/);
assert.match(template, /symbaroum-hud-maneuvers-toggle/);
assert.match(template, /data-action="maneuver"/);
assert.match(template, /#if rituals\.available/);
assert.match(template, /symbaroum-hud-rituals-toggle/);
assert.match(template, /data-ritual-drop="{{rituals\.canUse}}"/);
assert.match(template, /id="symbaroum-hud-rituals-panel"/);
assert.match(template, /symbaroum-hud-rituals-panel/);
assert.match(template, /data-action="toggle-rituals"/);
assert.match(template, /data-action="close-rituals"/);
assert.match(template, /data-action="select-ritual"/);
assert.match(template, /data-action="open-ritual"/);
assert.match(template, /class="symbaroum-hud-ability-add symbaroum-hud-ritual-add"/);
assert.match(template, /data-action="add-ritual"/);
assert.match(template, /class="symbaroum-hud-ritualist-header"/);
assert.match(template, /aria-labelledby="symbaroum-hud-ritualist-title"/);
assert.match(template, /<h2 id="symbaroum-hud-ritualist-title">/);
assert.match(template, /src="{{rituals\.ritualist\.img}}"/);
assert.match(template, /class="symbaroum-hud-ritualist-stats"/);
assert.match(template, /rituals\.ritualist\.levelLabel/);
assert.match(template, /rituals\.ritualist\.known/);
assert.match(template, /rituals\.ritualist\.capacity/);
assert.match(template, /rituals\.ritualist\.remaining/);
assert.match(template, /#if rituals\.ritualist\.canLearnAdditional[\s\S]*SYMBAROUMHUD\.Rituals\.BaseCapacity/);
assert.match(template, /SYMBAROUMHUD\.Rituals\.BaseRemaining/);
assert.match(template, /data-additional-allowed="{{rituals\.ritualist\.canLearnAdditional}}"/);
assert.match(template, /data-action="open-ability" data-item-id="{{rituals\.ritualist\.id}}"/);
assert.match(template, /SYMBAROUMHUD\.Rituals\.Progression/);
assert.ok(
  template.indexOf('class="symbaroum-hud-ritualist-header"')
    < template.indexOf('class="symbaroum-hud-abilities-body"'),
  "The Ritualist summary must appear above the ritual browser"
);
assert.match(template, /data-panel="rituals"/);
assert.match(template, /SYMBAROUMHUD\.Rituals\.List/);
assert.match(template, /SYMBAROUMHUD\.Rituals\.Empty/);
assert.match(template, /fa-book-open/);
assert.match(template, /#if mysticalPowers\.available/);
assert.match(template, /symbaroum-hud-mystical-powers-toggle/);
assert.match(template, /data-mystical-power-drop="{{mysticalPowers\.canUse}}"/);
assert.match(template, /id="symbaroum-hud-mystical-powers-panel"/);
assert.match(template, /symbaroum-hud-mystical-powers-panel/);
assert.match(template, /data-action="toggle-mystical-powers"/);
assert.match(template, /data-action="close-mystical-powers"/);
assert.match(template, /data-action="select-mystical-power"/);
assert.match(template, /data-action="select-mystical-power-tab"/);
assert.match(template, /data-action="use-mystical-power"/);
assert.match(template, /data-action="open-mystical-power"/);
assert.match(template, /data-item-uuid="{{mysticalPowers\.selected\.uuid}}"/);
assert.match(template, /#if mysticalPowers\.canUse}}draggable="true"/);
assert.match(template, /data-panel="mystical-powers"/);
assert.match(template, /SYMBAROUMHUD\.MysticalPowers\.List/);
assert.match(template, /SYMBAROUMHUD\.MysticalPowers\.Empty/);
assert.match(template, /fa-hand-sparkles/);
assert.match(template, /#if abilities\.available/);
assert.match(template, /class="symbaroum-hud-abilities-panel"/);
assert.match(template, /id="symbaroum-hud-traits-panel"/);
assert.match(template, /symbaroum-hud-traits-panel/);
assert.match(template, /#if traits\.available/);
assert.match(template, /symbaroum-hud-traits-toggle/);
assert.ok(
  template.indexOf('symbaroum-hud-traits-toggle')
    < template.indexOf('symbaroum-hud-maneuvers-toggle'),
  "The maneuvers HUD button must be the last dynamic knowledge button"
);
assert.match(template, /class="symbaroum-hud-abilities-body"/);
assert.match(template, /class="symbaroum-hud-ability-entry"/);
assert.match(template, /class="symbaroum-hud-ability-add"/);
assert.match(template, /data-ability-id="{{id}}"/);
assert.match(template, /data-action="add-ability"/);
assert.match(template, /class="symbaroum-hud-ability-detail"/);
assert.match(template, /class="symbaroum-hud-ability-description"/);
assert.match(template, /class="symbaroum-hud-ability-tabs"/);
assert.match(template, /class="symbaroum-hud-ability-tab"/);
assert.match(template, /class="symbaroum-hud-ability-tab-panel"/);
assert.match(template, /#if abilities\.selected\.hasLevels/);
assert.match(template, /data-action="select-ability-tab"/);
assert.match(template, /data-action="toggle-ability-level"/);
assert.match(template, /data-learned="{{learned}}"/);
assert.match(template, /class="symbaroum-hud-ability-active-toggle"/);
assert.match(template, /abilities\.selected\.activeTab\.learned/);
assert.match(template, /abilities\.selected\.activeTab\.description/);
assert.match(template, /class="symbaroum-hud-abilities-empty"/);
assert.match(template, /data-action="toggle-abilities"/);
assert.match(template, /data-action="toggle-traits"/);
assert.match(template, /data-trait-drop="{{traits\.canUse}}"/);
assert.match(template, /data-action="close-abilities"/);
assert.match(template, /data-action="close-traits"/);
assert.match(template, /data-action="select-ability"/);
assert.match(template, /data-action="select-trait"/);
assert.match(template, /#if traits\.selected\.hasLevels/);
assert.match(template, /data-action="select-trait-tab"/);
assert.match(template, /traits\.selected\.activeTab\.description/);
assert.match(template, /data-action="use-ability"/);
assert.match(template, /#if abilities\.selected\.canUsePower/);
assert.match(template, /data-action="use-trait"/);
assert.match(template, /#if traits\.selected\.canUsePower/);
assert.match(template, /data-action="open-ability"/);
assert.match(template, /data-panel="abilities"/);
assert.match(template, /data-item-uuid="{{uuid}}"/);
assert.match(template, /data-ability-draggable="{{\.\.\/abilities\.canUse}}"/);
assert.match(template, /#if \.\.\/abilities\.canUse}}draggable="true"/);
assert.match(template, /class="symbaroum-hud-storage-panel"/);
assert.match(template, /class="symbaroum-hud-storage-sidebar"/);
assert.match(template, /class="symbaroum-hud-storage-load"/);
assert.match(template, /class="symbaroum-hud-storage-title-img"/);
assert.match(template, /class="symbaroum-hud-quiver-page"/);
assert.match(template, /class="symbaroum-hud-quiver-detail"/);
assert.match(template, /class="symbaroum-hud-quiver-detail-info"/);
assert.match(template, /class="symbaroum-hud-quiver-loaded-list"/);
assert.match(template, /symbaroum-hud-quiver-ammo-items/);
assert.match(template, /class="symbaroum-hud-quiver-reload"/);
assert.match(template, /data-action="reload-quiver"/);
assert.match(template, /data-container-id="{{storageId}}"/);
assert.match(template, /#each storage\.quivers/);
assert.match(template, /storage\.quiver\.loaded/);
assert.match(template, /storage\.quiver\.loadedItems/);
assert.match(template, /SYMBAROUMHUD\.Storage\.AvailableAmmo/);
assert.match(template, /storage\.load\.current/);
assert.match(template, /storage\.load\.capacity/);
assert.match(template, /storage\.load\.penalty/);
assert.match(template, /data-action="toggle-storage"/);
assert.match(template, /data-action="select-storage-container"/);
assert.match(template, /data-action="open-storage-item"/);
assert.match(template, /data-action="delete-storage-item"/);
assert.match(template, /symbaroum-hud-storage-item-delete/);
assert.match(template, /data-action="toggle-storage-view"/);
assert.match(template, /data-view-mode="{{storage\.viewMode}}"/);
assert.equal(
  (template.match(/data-view-mode="{{storage\.viewMode}}"/g) ?? []).length,
  3
);
assert.match(template, /data-storage-drop-container="{{id}}"/);
assert.match(template, /data-storage-delete-container="{{id}}"/);
assert.match(template, /data-storage-withdraw-zone="inventory"/);
assert.match(template, /data-storage-inventory-drop="{{storage\.inventoryActive}}"/);
assert.match(template, /data-storage-draggable="{{draggable}}"/);
assert.match(template, /draggable="true"/);
assert.match(template, /class="symbaroum-hud-attributes"/);
assert.match(template, /class="symbaroum-hud-attribute-name">{{label}}/);
assert.match(template, /data-action="roll-attribute"/);
assert.match(template, /data-attribute="{{id}}"/);
assert.match(template, /class="symbaroum-hud-character-actions"/);
assert.match(template, /data-action="death-test"/);
assert.match(template, /data-action="death-recovery"/);
assert.match(template, /data-action="rest"/);
assert.match(template, /data-action="recover-ammo"/);
assert.match(template, /class="symbaroum-hud-ammo-recovery-slot"/);
assert.match(template, /ammoRecovery\.count/);
assert.match(template, /data-action="weapon-readiness"/);
assert.match(template, /data-action="roll-defense"/);
assert.match(template, /data-action="consume-ration"/);
assert.match(template, /class="symbaroum-hud-readiness-slot"/);
assert.match(application, /SETTINGS\.SHOW_WEAPON_READINESS_BUTTON/);
assert.match(template, /info\.defense/);
assert.match(template, /info\.armor/);
assert.match(template, /info\.rations/);
assert.match(template, /info\.rations\.usesRemaining/);
assert.match(template, /info\.rations\.usesPerUnit/);
assert.match(template, /#if info\.quiver/);
assert.match(template, /SYMBAROUMHUD\.Info\.Experience/);
assert.match(template, /SYMBAROUMHUD\.Info\.ExperienceShort/);
assert.match(template, /data-action="reroll-cost"/);
assert.match(template, /actions\.rerollCost/);
assert.doesNotMatch(template, /symbaroum-hud-ind-action/);
assert.match(template, /data-action="toggle-players"/);
assert.match(application, /document\.body\.appendChild/);
assert.match(application, /getElementById\("hotbar"\)/);
assert.match(application, /#dockHotbar\(content, hotbar\)/);
assert.match(application, /refreshHotbarShortcuts\(hotbar\)/);
assert.match(application, /rightControls\.before\(collapseToggle\)/);
assert.match(application, /collapseToggle\?\.addEventListener\("click"/);
assert.match(application, /hotbar\.querySelectorAll\("\.symbaroum-hud-collapse-toggle"\)/);
assert.match(application, /staleToggle\.remove\(\)/);
assert.match(application, /#animateHudCollapse/);
assert.match(application, /prefers-reduced-motion: reduce/);
assert.match(application, /duration: 180/);
assert.match(application, /const stableCharacterCard = this\.#collapseAnimationRunning/);
assert.match(application, /replaceWith\(stableCharacterCard\)/);
assert.match(application, /const stableHotbarControls = this\.#collapseAnimationRunning/);
assert.match(application, /replaceWith\(stableHotbarControls\)/);
assert.doesNotMatch(
  stylesheet,
  /data-hud-collapsed="true"[^}]*symbaroum-hud-hotbar-controls/
);
assert.doesNotMatch(stylesheet, /data-hud-transition="collapse"[^}]*symbaroum-hud-character-card/);
assert.match(application, /detachedHotbar \?\? document\.getElementById/);
assert.match(application, /#restoreHotbar\(\)/);
assert.match(application, /IndResourcesIntegration\.context/);
assert.match(application, /load: indResources\.load/);
assert.match(application, /moneyContext\(actor\)/);
assert.match(application, /actor\?\.system\?\.money/);
assert.match(application, /actions\?\.maneuvers/);
assert.match(application, /IndResourcesIntegration\.openStorageItem/);
assert.match(application, /IndResourcesIntegration\.deleteStorageItem/);
assert.match(application, /IndResourcesIntegration\.deleteStorageContainer/);
assert.match(application, /IndResourcesIntegration\.openMoney/);
assert.match(application, /#openRerollCostDialog\(actor\)/);
assert.match(application, /#openVitalityDialog\(actor\)/);
assert.match(application, /parseVitalityDelta/);
assert.match(application, /event\.key !== "Enter"/);
assert.match(application, /placeholder="\+3 \/ -9"/);
assert.match(application, /#openCorruptionDialog\(actor\)/);
assert.match(application, /ActorService\.adjust\([\s\S]*system\.health\.toughness\.value/);
assert.match(application, /ActorService\.adjust\([\s\S]*system\.health\.corruption\.temporary/);
assert.match(actorService, /CORRUPTION\.CHAT_THRESHOLD/);
assert.match(actorService, /addCondition\?\.\("dead"\)/);
assert.match(actorService, /CHAT\.DEAD/);
assert.match(actorService, /COMBAT\.CHAT_DAMAGE_DYING/);
assert.match(actorService, /game\.user\?\.isGM/);
assert.match(actorService, /controlledActors\.find/);
assert.match(application, /#openManeuverDialog\(actor\)/);
assert.match(application, /IndResourcesIntegration\.maneuvers\(\)/);
assert.match(application, /IndResourcesIntegration\.executeManeuver\(actor, maneuverId\)/);
assert.match(application, /data-maneuver-description-toggle/);
assert.match(application, /class="symbaroum-hud-maneuver-description"/);
assert.match(application, /render: setupManeuverPicker/);
assert.match(application, /function setupManeuverPicker\(html\)/);
assert.match(application, /SYMBAROUMHUD\.Maneuvers\.ShowDescription/);
assert.match(application, /SYMBAROUMHUD\.Maneuvers\.HideDescription/);
assert.match(application, /#openAddAbilityDialog\(actor\)/);
assert.match(application, /CharacterCreatorService\.openAbilityBrowser\(actor\)/);
assert.match(application, /#openAddRitualDialog\(actor\)/);
assert.match(application, /ActorService\.availableWorldRituals\(actor\)/);
assert.match(application, /ActorService\.buyWorldRitual\(actor, itemId\)/);
assert.match(application, /const abilitiesAvailable = Boolean\(actor\)/);
assert.match(application, /const traitsAvailable = Boolean\(actor\)/);
assert.match(application, /ActorService\.importTraitLikeItem\(actor, dropData\)/);
assert.match(application, /#canDropOnTraits\(dataTransfer\)/);
assert.match(application, /#clearTraitDropTargets\(root\)/);
assert.match(application, /setupAbilityPickerSearch/);
assert.match(application, /input\[name='abilitySearch'\]/);
assert.match(application, /ActorService\.payRerollCost\(actor, cost\)/);
assert.match(application, /SYMBAROUMHUD\.RerollCost\.Title/);
assert.match(application, /IndResourcesIntegration\.recoverAmmo/);
assert.match(application, /IndResourcesIntegration\.storeInContainer/);
assert.match(application, /IndResourcesIntegration\.withdrawFromContainer/);
assert.match(application, /IndResourcesIntegration\.importInventoryItem/);
assert.match(application, /IndResourcesIntegration\.importWeaponItem/);
assert.match(application, /IndResourcesIntegration\.isWeaponItem/);
assert.match(application, /IndResourcesIntegration\.importRitualItem/);
assert.match(application, /IndResourcesIntegration\.isRitualItem/);
assert.match(application, /IndResourcesIntegration\.reloadQuiver/);
assert.match(application, /#abilitiesOpen/);
assert.match(application, /#traitsOpen/);
assert.match(application, /#ritualsOpen/);
assert.match(application, /#selectedAbilityId/);
assert.match(application, /#selectedAbilityTab/);
assert.match(application, /#selectedTraitId/);
assert.match(application, /#selectedRitualId/);
assert.match(application, /DEFAULT_ABILITY_TAB/);
assert.match(application, /ACTION_LABEL_KEYS/);
assert.match(application, /actionLabel\(source\.action\)/);
assert.match(application, /learned: Boolean\(entry\?\.learned\)/);
assert.match(application, /isTraitLikeItem\(item\)/);
assert.match(application, /canUsePowerItem\(item\)/);
assert.match(application, /experienceContext\(actor\)/);
assert.match(application, /actor\?\.system\?\.experience\?\.experience/);
assert.match(application, /const available = number\(experience\.available/);
assert.match(application, /const knowledgeButtons = \[/);
assert.match(application, /const showPlayerResources = actor\?\.type === "player"/);
assert.match(application, /available: showPlayerResources \|\| knowledgeButtons > 0/);
assert.match(application, /showExperience: showPlayerResources/);
assert.match(application, /showEconomy: showPlayerResources/);
assert.match(application, /rations: showPlayerResources && indResources\.active \? indResources\.rations : null/);
assert.match(application, /columns: knowledgeButtons > 2 \? 2 : 1/);
assert.match(application, /isMysticalPowerItem\(item\) === mysticalPowers/);
assert.match(application, /mysticalPowers \|\| isTraitLikeItem\(item\) === traits/);
assert.match(application, /isRitualItem\(item\)/);
assert.match(application, /\.filter\(\(item\) => !isRitualItem\(item\)\)/);
assert.match(application, /available: items\.length > 0/);
assert.match(application, /hasLevels/);
assert.match(application, /#attacksOpen/);
assert.match(application, /abilityContext\(\s*actor,\s*this\.\#selectedAbilityId,\s*this\.\#selectedAbilityTab,\s*\{\s*traits: false\s*\}\s*\)/);
assert.match(application, /abilityContext\(\s*actor,\s*this\.\#selectedMysticalPowerId,\s*this\.\#selectedMysticalPowerTab,\s*\{\s*mysticalPowers: true\s*\}\s*\)/);
assert.match(application, /abilityContext\(\s*actor,\s*this\.\#selectedTraitId,\s*this\.\#selectedTraitTab,\s*\{\s*traits: true\s*\}\s*\)/);
assert.match(application, /hasPowerLevels\(item\)/);
assert.match(application, /ritualContext\(actor, this\.\#selectedRitualId\)/);
assert.match(application, /open: this\.\#abilitiesOpen && abilitiesAvailable/);
assert.match(application, /open: this\.\#mysticalPowersOpen && mysticalPowers\.available/);
assert.match(application, /open: this\.\#ritualsOpen && rituals\.available/);
assert.match(application, /open: this\.\#traitsOpen && traitsAvailable/);
assert.match(application, /findRitualistAbility\(actor\)/);
assert.match(application, /ritualistProgress\(/);
assert.match(application, /optionalMoreRituals/);
assert.match(application, /IndResourcesIntegration\.isRitualistAbility\(item\)/);
assert.match(application, /attackContext\(actor, \{[\s\S]*drawnWeapons: indResources\.drawnWeapons/);
assert.match(application, /actor\?\.system\?\.weapons/);
assert.match(application, /readinessContext\(drawnWeapons\)/);
assert.match(application, /readinessLabel/);
assert.match(application, /SYMBAROUMHUD\.Attacks\.Drawn/);
assert.match(application, /SYMBAROUMHUD\.Attacks\.Sheathed/);
assert.match(application, /normalizeText\(weapon\?\.name/);
assert.match(application, /item\?\.system\?\.isPower/);
assert.match(application, /abilityDetailContext\(selectedItem, selectedAbilityTab\)/);
assert.match(application, /selectedAbilityTab/);
assert.match(application, /foundry\?\.applications\?\.ux\?\.TextEditor/);
assert.match(application, /textEditor\.enrichHTML/);
assert.match(application, /game\.user\?\.isGM && actor\?\.type === "monster"/);
assert.match(application, /actor\.system\?\.bio\?\.tactics/);
assert.match(application, /action === "toggle-tactics"/);
assert.match(application, /#tacticsCollapsed/);
assert.match(application, /hasStatusSummary: Boolean\(tacticsHtml \|\| effects\.length\)/);
assert.match(application, /defenseDisplayValue\(actor\)/);
assert.match(application, /uuid: item\.uuid/);
assert.match(application, /data-ability-draggable="true"/);
assert.match(application, /abilityElement\.dataset\.itemUuid \|\| item\?\.uuid/);
assert.match(application, /data-weapon-draggable="true"/);
assert.match(application, /weaponElement\.dataset\.itemUuid/);
assert.match(application, /effectAllowed = "copy"/);
assert.match(application, /ActorService\.usePower/);
assert.match(application, /ActorService\.setAbilityLevelActive/);
assert.match(application, /ActorService\.openItem/);
assert.match(application, /ActorService\.rollWeapon/);
assert.match(application, /#rollWeapon\(actor, element\.dataset\.itemId\)/);
assert.match(application, /IndResourcesIntegration\.weaponReadinessState\(actor, itemId\)/);
assert.match(application, /IndResourcesIntegration\.drawWeapon\(actor, itemId\)/);
assert.match(application, /const drawn = await IndResourcesIntegration\.drawWeapon\(actor, itemId\);[\s\S]*if \(!drawn\) return null;[\s\S]*return this\.render\(\);/);
assert.doesNotMatch(application, /await this\.render\(\);\s*return ActorService\.rollWeapon\(actor, itemId\)/);
assert.match(application, /IndResourcesIntegration\.sheatheWeapon/);
assert.match(application, /SYMBAROUMHUD\.Attacks\.DrawMovementReminder/);
assert.match(stylesheet, /\.symbaroum-hud-draw-weapon-warning/);
assert.match(application, /#storageOpen/);
assert.match(application, /getStorageViewMode\(\)/);
assert.match(application, /SETTINGS\.STORAGE_VIEW_MODE/);
assert.match(application, /application\/x-tenebre-container-item/);
assert.match(application, /addEventListener\("dragstart"/);
assert.match(application, /addEventListener\("dragover"/);
assert.match(application, /addEventListener\("drop"/);
assert.match(application, /#canDropOnAttacks\(event\.dataTransfer\)/);
assert.match(application, /#clearAttackDropTargets\(root\)/);
assert.match(application, /#canDropOnRituals\(event\.dataTransfer\)/);
assert.match(application, /#clearRitualDropTargets\(root\)/);
assert.match(application, /type: "Item", uuid: item\.uuid/);
assert.match(application, /ATTRIBUTE_ORDER/);
assert.match(application, /attributeContext\(actor\)/);
assert.match(application, /activeEffectContext\(actor\)/);
assert.match(application, /addEventListener\("contextmenu"/);
assert.match(application, /ActorService\.removeEffect\(actor, effectId\)/);
assert.match(application, /SYMBAROUMHUD\.Actions\.RemoveEffect/);
assert.match(stylesheet, /inset: auto auto 8px 8px/);
assert.match(stylesheet, /#symbaroum-hud-hostility-tint/);
assert.match(stylesheet, /symbaroum-hud-hostility-pulse/);
assert.match(stylesheet, /prefers-reduced-motion/);
assert.match(stylesheet, /assets\/overlays\/low-health-blood\.png/);
assert.match(stylesheet, /assets\/overlays\/button-cracks\.png/);
assert.match(stylesheet, /grayscale\(0\.9\)/);
assert.match(stylesheet, /brightness\(1\.9\)/);
assert.match(stylesheet, /drop-shadow\(0 0 1px rgb\(255 255 255 \/ 78%\)\)/);
assert.match(stylesheet, /data-vitality-state="injured"/);
assert.match(stylesheet, /data-vitality-state="injured"[^}]+opacity: 0\.24/s);
assert.match(stylesheet, /data-vitality-state="wounded"/);
assert.match(stylesheet, /data-vitality-state="critical"/);
assert.doesNotMatch(stylesheet, /symbaroum-hud-card-row::after/);
assert.match(stylesheet, /width: 150px/);
assert.match(stylesheet, /object-fit: cover/);
assert.match(stylesheet, /\.symbaroum-hud-actor-cycle/);
assert.match(stylesheet, /button\.symbaroum-hud-actor-cycle \{[\s\S]*opacity: 0\.92;[\s\S]*pointer-events: auto;/);
assert.match(stylesheet, /\.symbaroum-hud-character-name:hover/);
assert.match(stylesheet, /\.symbaroum-hud-character-card:hover \.symbaroum-hud-character-name/);
assert.match(stylesheet, /\.symbaroum-hud-character-card:hover \.symbaroum-hud-character-resources/);
assert.match(stylesheet, /\.symbaroum-hud-character-card:focus-within \.symbaroum-hud-character-resources/);
assert.match(stylesheet, /\.symbaroum-hud-character-resource-fill/);
assert.match(stylesheet, /button\.symbaroum-hud-character-resource:hover/);
assert.match(stylesheet, /\.symbaroum-hud-vitality-dialog/);
assert.match(stylesheet, /\.symbaroum-hud-corruption-dialog/);
assert.match(stylesheet, /--symbaroum-hud-resource-percent/);
assert.match(template, /SYMBAROUMHUD\.Corruption\.Manage/);
assert.match(application, /total: totalCorruption/);
assert.match(stylesheet, /#ui-left-column-1 #players/);
assert.match(stylesheet, /body\.symbaroum-hud-hide-players #players/);
assert.match(stylesheet, /#hotbar #hotbar-controls-left/);
assert.match(stylesheet, /#hotbar #action-bar/);
assert.match(stylesheet, /--slot-color: rgb\(8 8 10 \/ 82%\)/);
assert.match(stylesheet, /#hotbar\.faded-ui[\s\S]*opacity: 1/);
assert.match(stylesheet, /#hotbar #action-bar \.slot/);
assert.match(stylesheet, /width: 586px/);
assert.match(stylesheet, /\.symbaroum-hud-main-column/);
assert.match(stylesheet, /\.symbaroum-hud-card-row \{[^}]+z-index: 4/s);
assert.match(stylesheet, /button\.symbaroum-hud-collapse-toggle/);
assert.match(stylesheet, /#hotbar > button\.symbaroum-hud-collapse-toggle/);
assert.match(stylesheet, /data-hud-collapsed="true"/);
assert.match(stylesheet, /data-hud-collapsed="true"[^}]+margin-left: 4px/s);
assert.match(stylesheet, /@keyframes symbaroum-hud-expand-reveal/);
assert.match(stylesheet, /@keyframes symbaroum-hud-compact-settle/);
assert.match(stylesheet, /data-hud-transition="expand"/);
assert.match(stylesheet, /\.symbaroum-hud-character-actions/);
assert.match(stylesheet, /--symbaroum-hud-side-button-height: 27\.1667px/);
assert.match(stylesheet, /\.symbaroum-hud-hotbar-controls \{[\s\S]*?height: 178px/);
assert.match(stylesheet, /height: var\(--symbaroum-hud-side-button-height\)/);
assert.match(stylesheet, /\.symbaroum-hud-hotbar-row/);
assert.match(stylesheet, /body:has\(#symbaroum-hud\) > #tenebre-weapon-readiness-floating/);
assert.match(stylesheet, /#tenebre-ammo-hud-left/);
assert.match(stylesheet, /\.symbaroum-hud-ammo-recovery-slot/);
assert.match(stylesheet, /\.symbaroum-hud-info-panel/);
assert.match(stylesheet, /\.symbaroum-hud-economy-panel/);
assert.match(stylesheet, /\.symbaroum-hud-economy-entry/);
assert.match(stylesheet, /\.symbaroum-hud-experience-panel/);
assert.match(stylesheet, /\.symbaroum-hud-reroll-dialog/);
assert.match(stylesheet, /button\.symbaroum-hud-experience-panel:hover/);
assert.match(stylesheet, /\.symbaroum-hud-experience-panel \{[\s\S]*?width: 100%/);
assert.match(stylesheet, /\.symbaroum-hud-experience-panel \{[\s\S]*?grid-column: 1 \/ -1/);
assert.doesNotMatch(stylesheet, /width: calc\(100% \+ 49px\)/);
assert.doesNotMatch(stylesheet, /margin-left: -49px/);
assert.match(stylesheet, /\.symbaroum-hud-panel-toggle/);
assert.match(stylesheet, /\.symbaroum-hud-maneuvers-toggle/);
assert.match(stylesheet, /\.symbaroum-hud-maneuver-picker-entry/);
assert.match(stylesheet, /\.symbaroum-hud-maneuver-picker-choice/);
assert.match(stylesheet, /\.symbaroum-hud-maneuver-description-toggle/);
assert.match(stylesheet, /\.symbaroum-hud-maneuver-description/);
assert.match(stylesheet, /\.symbaroum-hud-occupation-art figcaption \{[^}]*font-size: 0\.72rem;[^}]*line-height: 1\.35;/s);
assert.match(stylesheet, /\.symbaroum-hud-occupation-reading-page > footer \{[^}]*font-size: 0\.72rem;[^}]*line-height: 1\.35;/s);
assert.match(stylesheet, /\.symbaroum-hud-shadow-book/);
assert.match(characterCreatorTheme, /\.symbaroum-hud-attribute-occupation-recommendation/);
assert.match(stylesheet, /\.symbaroum-hud-race-art \{[^}]*position: relative;[^}]*align-self: start;/s);
assert.doesNotMatch(stylesheet, /\.symbaroum-hud-race-art \{[^}]*position: sticky;/s);
assert.match(stylesheet, /\.symbaroum-hud-race-trait-card \{[^}]*min-height: 58px;[^}]*grid-template-columns: 40px minmax\(0, 1fr\) 26px;/s);
assert.match(stylesheet, /\.symbaroum-hud-race-trait-card > i \{[^}]*width: 40px;[^}]*background:/s);
assert.match(stylesheet, /\.symbaroum-hud-race-trait-control \{[^}]*grid-column: 3;[^}]*background: transparent;/s);
assert.match(stylesheet, /\.symbaroum-hud-race-trait-control:has\(input:checked\)::before/);
assert.match(stylesheet, /\.symbaroum-hud-race-lore-section dl > div \{[^}]*display: block;[^}]*background: transparent;/s);
assert.match(stylesheet, /\.symbaroum-hud-race-lore-section dd \{[^}]*overflow-wrap: anywhere;/s);
assert.match(stylesheet, /\.symbaroum-hud-ability-index-label > small/);
assert.match(stylesheet, /data-occupation-recommended="true"/);
assert.match(stylesheet, /\.symbaroum-hud-shadow-principles/);
assert.match(stylesheet, /\.symbaroum-hud-shadow-example/);
assert.match(stylesheet, /\.symbaroum-hud-shadow-index/);
assert.match(stylesheet, /\.symbaroum-hud-shadow-reading-page/);
assert.match(stylesheet, /\.symbaroum-hud-shadow-art/);
assert.match(stylesheet, /\.symbaroum-hud-action-area \{[\s\S]*?grid-template-columns: 44px auto/);
assert.match(stylesheet, /\.symbaroum-hud-action-area \{[\s\S]*?grid-template-rows: 19px auto/);
assert.match(stylesheet, /\.symbaroum-hud-panel-stack/);
assert.match(stylesheet, /\.symbaroum-hud-knowledge-stack/);
assert.match(stylesheet, /data-knowledge-columns="1"[\s\S]*width: 44px/);
assert.match(stylesheet, /data-has-experience="false"[\s\S]*grid-template-rows: auto/);
assert.match(stylesheet, /grid-template-columns: 44px/);
assert.match(stylesheet, /grid-auto-rows: 44px/);
assert.match(stylesheet, /\.symbaroum-hud-rituals-toggle/);
assert.match(stylesheet, /data-ritual-drop-target="true"/);
assert.match(stylesheet, /\.symbaroum-hud-mystical-powers-toggle/);
assert.match(stylesheet, /data-mystical-power-drop-target="true"/);
assert.match(stylesheet, /\.symbaroum-hud-traits-toggle/);
assert.match(stylesheet, /data-trait-drop-target="true"/);
assert.match(stylesheet, /\.symbaroum-hud-attacks-toggle/);
assert.match(stylesheet, /data-weapon-drop-target="true"/);
assert.match(stylesheet, /\.symbaroum-hud-attacks-panel/);
assert.match(stylesheet, /\.symbaroum-hud-attacks-body/);
assert.match(stylesheet, /grid-auto-flow: row/);
assert.match(stylesheet, /grid-auto-rows: 150px/);
assert.match(stylesheet, /grid-template-columns: repeat\(auto-fill, minmax\(170px, 1fr\)\)/);
assert.match(stylesheet, /\.symbaroum-hud-attack-entry/);
assert.match(stylesheet, /\.symbaroum-hud-attack-label/);
assert.match(stylesheet, /\.symbaroum-hud-attack-readiness/);
assert.match(stylesheet, /data-readiness-known="true"\]\[data-drawn="true"/);
assert.match(stylesheet, /data-readiness-known="true"\]\[data-drawn="false"/);
assert.match(stylesheet, /data-weapon-draggable="true"/);
assert.match(stylesheet, /\.symbaroum-hud-attacks-empty/);
assert.match(stylesheet, /\.symbaroum-hud-abilities-panel/);
assert.match(stylesheet, /\.symbaroum-hud-rituals-panel/);
assert.match(stylesheet, /\.symbaroum-hud-ritualist-header/);
assert.match(stylesheet, /\.symbaroum-hud-ritualist-stats/);
assert.match(stylesheet, /\.symbaroum-hud-ritualist-rules/);
assert.match(
  stylesheet,
  /@media \(max-width: 760px\)[\s\S]*\.symbaroum-hud-ritualist-stats[\s\S]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/
);
assert.match(stylesheet, /data-at-capacity="true"/);
assert.match(stylesheet, /\.symbaroum-hud-mystical-powers-panel/);
assert.match(stylesheet, /\.symbaroum-hud-traits-panel/);
assert.match(stylesheet, /\.symbaroum-hud-abilities-body/);
assert.match(stylesheet, /\.symbaroum-hud-abilities-sidebar/);
assert.match(stylesheet, /overflow-y: auto/);
assert.match(stylesheet, /\.symbaroum-hud-ability-entry/);
assert.match(stylesheet, /flex: 0 0 54px/);
assert.match(stylesheet, /\.symbaroum-hud-ability-add/);
assert.match(stylesheet, /\.symbaroum-hud-ability-picker/);
assert.match(stylesheet, /\.symbaroum-hud-ability-picker-search/);
assert.match(stylesheet, /\.symbaroum-hud-ability-picker-empty/);
assert.match(stylesheet, /\.symbaroum-hud-ability-detail/);
assert.match(stylesheet, /\.symbaroum-hud-ability-description/);
assert.match(stylesheet, /\.symbaroum-hud-ability-tabs/);
assert.match(stylesheet, /\.symbaroum-hud-ability-tab/);
assert.match(stylesheet, /\.symbaroum-hud-ability-tab-panel/);
assert.match(stylesheet, /\.symbaroum-hud-ability-level-controls/);
assert.match(stylesheet, /\.symbaroum-hud-ability-active-toggle/);
assert.match(stylesheet, /data-learned="true"/);
assert.match(stylesheet, /data-ability-draggable="true"/);
assert.match(stylesheet, /symbaroum-hud-ability-detail-title[\s\S]*data-ability-draggable="true"/);
assert.match(stylesheet, /data-active="true"/);
assert.match(stylesheet, /\.symbaroum-hud-abilities-empty/);
assert.match(stylesheet, /\.symbaroum-hud-storage-panel/);
assert.match(stylesheet, /\.symbaroum-hud-storage-load/);
assert.match(stylesheet, /\.symbaroum-hud-storage-title-img/);
assert.match(stylesheet, /\.symbaroum-hud-storage-item-main/);
assert.match(stylesheet, /\.symbaroum-hud-storage-item-delete/);
assert.match(stylesheet, /:focus-within \.symbaroum-hud-storage-item-delete/);
assert.match(stylesheet, /\.symbaroum-hud-quiver-page/);
assert.match(stylesheet, /\.symbaroum-hud-quiver-detail/);
assert.match(stylesheet, /\.symbaroum-hud-quiver-loaded-list/);
assert.match(stylesheet, /\.symbaroum-hud-quiver-ammo-items/);
assert.match(stylesheet, /\.symbaroum-hud-quiver-reload/);
assert.match(stylesheet, /data-overloaded="true"/);
assert.match(stylesheet, /data-immobilized="true"/);
assert.match(stylesheet, /\.symbaroum-hud-storage-sidebar/);
assert.match(stylesheet, /\.symbaroum-hud-storage-view-toggle/);
assert.match(stylesheet, /data-view-mode="list"/);
assert.match(stylesheet, /grid-template-columns: 185px minmax\(0, 1fr\)/);
assert.match(stylesheet, /data-storage-drop-target="true"/);
assert.match(stylesheet, /data-storage-withdraw-target="true"/);
assert.match(stylesheet, /data-storage-inventory-target="true"/);
assert.match(stylesheet, /data-storage-draggable="true"/);
assert.match(stylesheet, /bottom: calc\(100% \+ 10px\)/);
assert.match(stylesheet, /\.symbaroum-hud-storage-panel[\s\S]*left: 0/);
assert.match(stylesheet, /\.symbaroum-hud-attacks-panel[\s\S]*left: 0/);
assert.match(stylesheet, /\.symbaroum-hud-abilities-panel,[\s\S]*\.symbaroum-hud-rituals-panel,[\s\S]*\.symbaroum-hud-mystical-powers-panel,[\s\S]*\.symbaroum-hud-traits-panel[\s\S]*left: calc\(-1 \* \(24px \+ 6px \+ 150px \+ 6px\)\)/);
assert.match(stylesheet, /width: min\(760px, calc\(100vw - 16px\)\)/);
assert.match(stylesheet, /\.symbaroum-hud-attributes/);
assert.match(stylesheet, /width: 220px/);
assert.match(stylesheet, /height: 117px/);
assert.match(stylesheet, /grid-template-rows: repeat\(4, minmax\(0, 1fr\)\)/);
assert.match(stylesheet, /\.symbaroum-hud-attribute/);
assert.match(stylesheet, /\.symbaroum-hud-attribute-name/);
assert.match(stylesheet, /width: 68px/);
assert.match(stylesheet, /width: 82px/);
assert.match(stylesheet, /\.symbaroum-hud-info-action/);
assert.match(stylesheet, /grid-template-columns: minmax\(0, 1fr\)/);
assert.match(stylesheet, /grid-auto-rows: minmax\(0, 1fr\)/);
assert.match(stylesheet, /\.symbaroum-hud-info-entry \+ \.symbaroum-hud-info-entry/);
assert.match(template, /data-hotbar-action="mute"/);
assert.match(template, /data-hotbar-action="menu"/);
assert.equal((template.match(/data-symba-delayed-tooltip/g) ?? []).length, 3);
assert.match(application, /HOTBAR_CONTROL_ACTIONS/);
assert.match(application, /CONTROL_TOOLTIP_DELAY_MS = 800/);
assert.match(application, /SETTINGS\.COLLAPSED/);
assert.match(application, /#listenerAbortController/);
assert.match(application, /#manualActorKey/);
assert.match(application, /#cycleActor/);
assert.match(application, /#updateHostilityTint/);
assert.match(application, /symbaroum-hud-hostility-tint/);
assert.match(application, /shouldShowDangerTint/);
assert.match(application, /new AbortController\(\)/);
assert.match(application, /addEventListener\("click",[\s\S]*\{ signal \}/);
assert.match(application, /game\.tooltip\.activate/);
assert.match(application, /applyPlayerListVisibility\(hidden\)/);
assert.match(application, /#updatePlayerToggle/);
assert.match(application, /if \(resolvedActor\) this\.#actor = resolvedActor/);
assert.match(application, /icons\/svg\/mystery-man\.svg/);
assert.match(application, /nbrOfFailedDeathRoll/);

function translationKeys(value, prefix = "") {
  return Object.entries(value ?? {})
    .flatMap(([key, entry]) => {
      const path = prefix ? `${prefix}.${key}` : key;
      if (!entry || typeof entry !== "object" || Array.isArray(entry)) return [path];
      return translationKeys(entry, path);
    })
    .sort();
}

function scriptFiles(directory) {
  return fs.readdirSync(directory, { withFileTypes: true })
    .flatMap((entry) => {
      const file = path.join(directory, entry.name);
      if (entry.isDirectory()) return scriptFiles(file);
      return entry.isFile() && file.endsWith(".mjs") ? [file] : [];
    });
}
assert.match(stylesheet, /\.symbaroum-hud-death-failures/);
assert.match(stylesheet, /\.symbaroum-hud-effects/);
assert.match(stylesheet, /\.symbaroum-hud-effect/);
assert.match(stylesheet, /\.symbaroum-hud-status-summary/);
assert.match(stylesheet, /\.symbaroum-hud-tactics-content/);
assert.match(stylesheet, /\.symbaroum-hud-tactics-toggle/);
assert.match(stylesheet, /data-tactics-collapsed="true"/);
assert.match(stylesheet, /\.symbaroum-hud-tactics \{[^}]+var\(--symbaroum-hud-title\) repeat/s);
assert.match(stylesheet, /\.symbaroum-hud-tactics-content \{[^}]+var\(--symbaroum-hud-paper\) repeat/s);
assert.match(stylesheet, /\.symbaroum-hud-effect-context-menu/);
assert.match(main, /registerHotbarShortcuts\(\)/);
assert.match(main, /registerCharacterCreatorHooks\(\)/);
assert.match(characterCreatorService, /Hooks\.on\("getActorSheetHeaderButtons"/);
assert.match(characterCreatorService, /Hooks\.on\("renderActorSheet"/);
assert.match(characterCreatorService, /attachCharacterCreatorHeaderButton/);
assert.match(characterCreatorService, /CharacterCreatorService\.open\(actor\)/);
assert.match(characterCreatorService, /symbaroum-hud-character-creator-choice-dialog/);
assert.match(characterCreatorTheme, /background\/orange_light\.webp/);
assert.match(stylesheet, /\.symbaroum-hud-open-character-creator/);
assert.match(stylesheet, /\.symbaroum-hud-occupation-art \{[\s\S]*?grid-template-rows: minmax\(0, 1fr\) auto/);
assert.match(stylesheet, /\.symbaroum-hud-occupation-art figcaption \{[\s\S]*?position: relative;[\s\S]*?grid-area: 2 \/ 1/);
assert.match(stylesheet, /\.symbaroum-hud-race-lore-section dt \{[\s\S]*?display: inline;[\s\S]*?font-family: var\(--font-serif/);
assert.match(stylesheet, /\.symbaroum-hud-race-lore-section dd \{[\s\S]*?display: inline;/);
assert.match(characterCreatorService, /Hooks\.on\("renderSymbaroumActorSheet"/);
assert.match(characterCreatorService, /characterCreationMode/);
assert.match(characterCreatorService, /DialogV2\.wait/);
assert.match(characterCreatorService, /CHARACTER_CREATION_MODES\.CREATOR/);
assert.match(characterCreatorService, /CHARACTER_CREATION_MODES\.MANUAL/);
assert.match(characterCreatorService, /system\.bio\.occupation/);
assert.match(characterCreatorService, /characterCreatorState/);
assert.match(characterCreatorService, /completedSteps: markCreatorStepComplete/);
assert.match(characterCreatorService, /choose-occupation/);
assert.match(coreOccupations, /CORE_OCCUPATIONS/);
assert.equal((coreOccupations.match(/occupation\("/g) ?? []).length, 15);
assert.match(coreOccupations, /quote: `\$\{prefix\}\.Quote`/);
assert.match(coreOccupations, /attributes: `\$\{prefix\}\.Attributes`/);
assert.match(characterCreatorService, /symbaroum-hud-creator-step-guide/);
assert.match(characterCreatorService, /data-occupation-id/);
assert.match(characterCreatorService, /data-occupation-id="custom"/);
assert.match(characterCreatorService, /customOccupationFromForm/);
assert.match(characterCreatorService, /data-open-occupation-ability/);
assert.match(characterCreatorService, /occupationAbilityDocument/);
assert.match(characterCreatorService, /dialog\.bringToFront/);
assert.match(characterCreatorService, /openCreationItemSheet\(item\)/);
assert.match(characterCreatorService, /classList\.add\("symbaroum-hud-creation-item-preview"\)/);
assert.match(characterCreatorService, /openShadowStep/);
assert.match(characterCreatorService, /#showShadowBook/);
assert.match(characterCreatorService, /"system\.bio\.shadow": shadow/);
assert.match(characterCreatorService, /furthestCreatorProgress\(previous\.step, SHADOW_STEP_COMPLETE\)/);
assert.match(characterCreatorService, /data-shadow-example/);
assert.match(characterCreatorService, /openEquipmentStep/);
assert.match(characterCreatorService, /#showEquipmentBook/);
assert.match(characterCreatorService, /"system\.money\.thaler": thaler/);
assert.match(characterCreatorService, /startingThalerForExperience/);
assert.match(characterCreatorService, /campingequipment/);
assert.match(characterCreatorService, /data-equipment-grant/);
assert.match(characterCreatorService, /openAttributesStep/);
assert.match(characterCreatorService, /choose-attributes/);
assert.match(characterCreatorService, /system\.attributes\.\$\{attribute\.id\}\.value/);
assert.match(characterCreatorService, /data-attribute-mode="typical"/);
assert.match(characterCreatorService, /data-attribute-mode="point-buy"/);
assert.match(characterCreatorService, /data-points-remaining/);
assert.match(characterCreatorService, /confirm\.disabled/);
assert.match(coreAttributes, /ATTRIBUTE_POINT_TOTAL = 80/);
assert.match(coreAttributes, /TYPICAL_ATTRIBUTE_VALUES/);
assert.equal((coreAttributes.match(/attribute\("/g) ?? []).length, 8);
assert.match(stylesheet, /\.symbaroum-hud-attributes-book/);
assert.match(stylesheet, /\.symbaroum-hud-attribute-mode-tabs/);
assert.match(stylesheet, /\.symbaroum-hud-attribute-choice-grid/);
assert.match(settings, /scope: "client"[\s\S]*config: false[\s\S]*STORAGE_VIEW_MODES\.GRID/);
assert.match(main, /registerHotbarShortcutKeybindings\(\)/);
assert.match(hotbarShortcuts, /Hooks\.on\("hotbarDrop"/);
assert.match(hotbarShortcuts, /return false/);
assert.match(hotbarShortcuts, /game\.keybindings\.register/);
assert.match(hotbarShortcuts, /KEYBINDING_PRECEDENCE\.DEFERRED/);
assert.match(hotbarShortcuts, /handleHotbarDrop\(hotbar, data, slot\)/);
assert.match(hotbarShortcuts, /export function refreshHotbarShortcuts/);
assert.match(hotbarShortcuts, /hotbarRoot\(element\)/);
assert.match(hotbarShortcuts, /if \(hotbar\?\.locked\) return false/);
assert.match(hotbarShortcuts, /addEventListener\("dragover"/);
assert.match(hotbarShortcuts, /addEventListener\("drop"/);
assert.match(hotbarShortcuts, /readDragData\(event\)/);
assert.match(hotbarShortcuts, /symbaroum-hud-document-shortcut/);
assert.match(hotbarShortcutService, /game\.user\.setFlag\(MODULE_ID, FLAG/);
assert.match(hotbarShortcutService, /setActorResolver/);
assert.match(hotbarShortcutService, /actors\[key\]/);
assert.match(hotbarShortcutService, /assignHotbarMacro\(game\.user, null/);
assert.match(hotbarShortcutService, /ActorService\.rollWeapon/);
assert.match(hotbarShortcutService, /document\.sheet\.render\(true\)/);
assert.match(hotbarCompat, /game\.release\?\.generation/);
assert.match(hotbarCompat, /user\.assignHotbarMacro\(macro, slot, fromSlot\)/);
assert.match(hotbarCompat, /user\.assignHotbarMacro\(macro, slot, \{ fromSlot \}\)/);
assert.match(stylesheet, /\.symbaroum-hud-document-shortcut/);
assert.match(stylesheet, /\.symbaroum-hud-shortcut-context-menu/);
assert.match(stylesheet, /Official Symbaroum sheet theme/);
assert.match(stylesheet, /\/systems\/symbaroum\/fonts\/Primitive-4yGY\.ttf/);
assert.match(stylesheet, /\/systems\/symbaroum\/asset\/image\/foreground\.webp/);
assert.match(stylesheet, /\/systems\/symbaroum\/asset\/image\/background\/title\.webp/);
assert.match(stylesheet, /\/systems\/symbaroum\/asset\/image\/background\/red_square_light\.webp/);
assert.match(stylesheet, /\/systems\/symbaroum\/asset\/image\/background\/green_gold_dark\.webp/);
assert.match(stylesheet, /font-family: "Philosopher"/);
assert.doesNotMatch(hooks, /canvasTearDown/);

console.log("Symbaroum HUD module structure: OK");
